# Generated by Django 3.2.9 on 2022-02-22 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100, verbose_name='Enter your shops name')),
                ('contact', models.CharField(max_length=100, verbose_name='Enter your shops contact')),
                ('commodities', models.CharField(max_length=200, verbose_name='Shop category')),
                ('location', models.CharField(max_length=200, verbose_name='Shops location')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
